spring:
  application:
    name: payment-service-app
  datasource:
    url: jdbc:postgresql://localhost:5436/payment_service_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8240

rabbitmq:
  order:
    queue:
      name: Order-Queue
    exchange:
      name: Order-Exchange
    routing:
      key: Order-Routing-Key
  payment:
    queue:
      name: Payment-Queue